services:
  postgres_cadastro:
    container_name: postgres_cadastro_msfood
    image: postgres:15.4
    environment: 
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"
  postgres_marketplace:
    container_name: postgres_marketplace_msfood
    image: postgres:15.4
    environment: 
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
    ports:
      - "5433:5432"
  jaeger_ifood: 
        container_name: jaeger_msfood
        image: jaegertracing/all-in-one:1.49
        ports:
          - "5775:5775/udp"
          - "6831:6831/udp"
          - "6832:6832/udp"
          - "5778:5778"
          - "16686:16686"
          - "14268:14268"
          - "9411:9411"
  grafana_ifood:
    container_name: grafana_msfood
    image: grafana/grafana:10.1.2
    ports: 
        - "3000:3000"
  artemis_ifood:
    container_name: artemis_ifood
    image: vromero/activemq-artemis:2.11.0
    environment: 
      ARTEMIS_USERNAME: guest
      ARTEMIS_PASSWORD: guest
    ports: 
        - "5672:5672"
        - "8161:8161"