services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:15.4
    environment: 
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"